version: "3"
services:
  ganache:
    env_file:
      - .env
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    entrypoint:
      - node
      - ./build/cli.node.js
      - --deterministic
      - --mnemonic
      - "minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef"
      - --networkId
      - "5777"
  # ipfs:
  #   env_file:
  #     - .env
  #   container_name: ipfs
  #   image: ipfs/go-ipfs:latest
  #   ports:
  #     - "8080:8080"
  #     - "5001:5001"
