version: "3"
services:
  ganache:
    env_file:
      - .env
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
  # ipfs:
  #   env_file:
  #     - .env
  #   container_name: ipfs
  #   image: ipfs/go-ipfs:latest
  #   ports:
  #     - "8080:8080"
  #     - "5001:5001"
