name: Ganache

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: "60s"
      - name: Check running containers
      - run: docker ps
      - run: curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":0}' http://localhost:8545
